apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: granite-code-model

resources:
  - namespace.yml
  - secret.yml
  - serving-runtime.yml
  - inference-service.yml
  - route.yml
